### ISSUE TITLE
Descriptions / Instructions

### ISSUE THREAD

**Issue by RainerBielefeld** [JustOff/github-wc-polyfill#16]
Can we get a USER-friendly description what this add-on does?

**Comment by JustOff** [comment]
What part of the current description seems user-hostile to you?

**Comment by bushy555** [comment]
> What part of the current description seems user-hostile to you?
For us absolute dummies that knows absolute nothing about anything,, a nice simple 25 word description of what to do with these files would be nice - just to get this working.  

I note in the batch file, your use of SED and ZIP.  Is this just only for Linux?   Instructions on O/S that this supports would be grand. Clearly it wont work on my XP straight-out-pf-the box. And there are no instructions or comments advising on what platform this will even work. A lot of people writing code on github ignore , or, dont even think about the destined platform... they appear to just assume that everyone is on their same platform, or , just somehow can read their own minds.  This happens so often.

Eg:
1. For Linux x32. Wont work on Winblows x32/x64.
2. Download, and shove it into this directory.
3. Do this and run this file to make it work.

The above is a very rough example, that is far more descriptive than the current wording inyour  readme.md on how to install.

cheers,

**Comment by micwoj92** [comment]
> Eg:
> 
>     1. For Linux x32. Wont work on Winblows x32/x64.
> 
>     2. Download, and shove it into this directory.
> 
>     3. Do this and run this file to make it work.
> 
> 
> The above is a very rough example, that is far more descriptive than the current wording inyour readme.md on how to install.
> 
> cheers,

There are no instructions because you literally have to click on the blue text (hyperlink to releases page) and then on the file which ends with .xpi. And BOOM, installed. Same as with any other addon, and this one has no configuration whatsoever.

If you use Windows XP then you are probably not using any of supported browsers. UXP does not support XP for a long time now, no idea about Seamonkey, never used it on Windows. 
And if you are "tech savvy" enough to still use winxp these days, well, you are on your own. System has been unsupported for like 7 years now, only on life-support due to tech enthusiasts and I bet you that most of them don't use it on everyday machines.

**Comment by bushy555** [comment]
Copy that, thanks.   Instructions : Run the .XPI file.

Is for a current XP supported browser called : MyPal.   Also will work for k-meleon. Repositry for MyPal is on Github. Your project is linked from and is recommended to fix an issue over on the MyPal repositry page. Apparently Polyfil works fine with both MyPal, PaleMoon and K-Meleon browsers, Weirdly coincidentally bizarringly ironically enough, it was to fix GitHub login scripts from this browser.

> UXP does not support XP for a long time now,
Cant really comment, other than I, along with tens of others, have been advised to install your polyfill add-on to make Github login work.

Offtopic : Betcha that there are way more installs of XP out there than what most people think.

All good, Thanks.  Apologies for being 'hostile' somewhat. Wasn't intentional.
This can be closed off (again)
