### ISSUE TITLE
Don't use an encoded & minified blob, but use a resource instead

### ISSUE THREAD

**Issue by wolfbeast** [JustOff/github-wc-polyfill#2]
This would make the extension a lot more transparent to evaluate.
Adding resource:// to the CSP is 100% safe (actually marginally safer than doing the hash dance) since those are browser internals.
Local resources also don't have to be minified which makes it fully readable for anyone needing to vet/evaluate the extension before installation/approval.

**Comment by JustOff** [comment]
I tried loading the polyfill from `resource://`, but unfortunately this gives very unstable results, probably due to a some race condition.

The one who wants to examine the polyfill source can find it on the [official project page](https://github.com/webcomponents/polyfills/tree/master/packages/webcomponentsjs). At the moment I'm using version 2.4.4 taken from [unpkg](https://unpkg.com/browse/@webcomponents/webcomponentsjs@2.4.4/).

**Comment by wolfbeast** [comment]
Hmm... I guess given the intricacies of parallel loading of external sources (especially when GitHub uses `async`) it might be unstable to link a resource `src` directly; but you could still improve this by loading from a resource, hashing, and then storing both in an object upon browser/extension init, then inject whatever blob you created. I know it'd be a little more work but it would greatly put everyone's mind at ease not having cryptic unreadable encoded blobs in an extension.

**Comment by JustOff** [comment]
I'm afraid this will not work, because the polyfill sources are written in typescript, and have a rather complex build system that does not provide for the generation of unminified javascript code.

To clarify the "cryptic unreadable encoded blobs" I wrote a simple Node.js script that processes and injects the polyfill from the `@webcomponents/webcomponentsjs` package into the `bootstrap.js` file so that anyone can easily verify that the extension is using the proper code from the original devs.

I think this is the best that could be done about this.

**Comment by SeaHOH** [comment]
I have loaded polyfill via `fetch`, and try use `resource://gre/modules/services-crypto/utils.js` to generate its hash, but the hash resoult is incorrect. Do you know why?
```javascript
btoa(CryptoUtils.UTF8AndSHA256("polyfill content ..."))
```

**Comment by JustOff** [comment]
Because it's preprocessed:

https://github.com/JustOff/github-wc-polyfill/blob/45d9408f4803441016b5fd924056baa26ae29034/update_polyfill.js#L14-L15

**Comment by SeaHOH** [comment]
Sorry, I does not made a detailed description. I knew you has minified it, but I try package the origine file.
The correct hash of polyfill content which I input could be `xBSLLB1cDJiybTvAHqFUlTZhbu1sq0ExdWu42xA5974=`, but my code resoult another one. Is `CryptoUtils.UTF8AndSHA256` a correctly using?

**Comment by JustOff** [comment]
```javascript
Cu.import("resource://gre/modules/NetUtil.jsm");
Cu.import("resource://gre/modules/services-crypto/utils.js");

var url = "https://unpkg.com/@webcomponents/webcomponentsjs@2.4.4/webcomponents-bundle.js";

NetUtil.asyncFetch(url, function(inputStream, status) {
  var bdata = NetUtil.readInputStreamToString(inputStream, inputStream.available());
  bdata = bdata.replace(/\/\*(\r?\n|\*)[\s\S]+?\*\//g, "");
  bdata = bdata.replace(/(\r?\n)+\/\/[\s\S]+/, "").trim();
  console.log(btoa(CryptoUtils.UTF8AndSHA256(bdata)));
});
```

**Comment by SeaHOH** [comment]
Thanks, I'll check my process.
