### ISSUE TITLE
GitLab broke again (SyntaxError: invalid regexp group)

### ISSUE THREAD

**Issue by dilworks** [JustOff/github-wc-polyfill#28]
It just seems GitLab just landed its latest load of Chromeisms™, breaking the site for us SeaMonkey users (at the very least), even with your great addon.

The error for today is:

> SyntaxError: invalid regexp group  21.4fceb368.chunk.js:1:37724

...which points to the following regex:
`Re=/^&(?<iid>\d+)$/`

I'm no regex guru so I can't tell what's wrong, but is this one even workable around?

**UPDATE:** Checked what that regexp does: it looks for digits preceded by an & character (i.e.: &12345 would match), while the ?<iid> part means that this capture group is named (the name being "iid"). That's only supported on Firefox starting at version 78, so I dunno what would be a possible workaround (fwiw, this regex works fine online regex testers like regex101, even on SeaMonkey)

**Comment by JustOff** [comment]
Unfortunately, this error cannot be eliminated by polyfill, it requires [RegExp engine update](https://hacks.mozilla.org/2020/06/a-new-regexp-engine-in-spidermonkey/) in the browser.

As a dirty workaround, you can get rid of the regex above using the [Modify HTTP Response](https://github.com/JustOff/modify-http-response) with the following filter:

```
[["gitlab.com",["/\\/assets\\/webpack\\/.+\\.chunk\\.js/",["(?<iid>","("]]]]
```

It makes GitLab perform basic operations normally, but I don't know which part remains broken.

**Comment by Vangelis66** [comment]
> It **just** seems GitLab just landed its latest load of Chromeisms™, 
> breaking the site for us **SeaMonkey** users (at the very least), even with your great addon.

True, several aspects of **GitLab** became "broken" for users of browsers with so-called **"legacy"** engines, mainly **WaterFox Classic**, **SeaMonkey** and **UXP**-based browsers (**Pale Moon**, **Basilisk** and forks), even with the latest version (**1.2.3**) of this superb extension :+1: ; mind you, **GitHub** themselves haven't stayed idle (many under-the-hood changes during these last two months), I'm surprised **GitHub** pages still work in my Basilisk fork... 

The **WaterFox Classic** community is usually more vocal 👍 , so in mid-June they created the following GL issue: 

https://gitlab.com/gitlab-org/gitlab/-/issues/333598

Back then, I was still able to access that issue page with **Pale Moon 29** (this extension installed 😉 ), I even [commented](https://gitlab.com/gitlab-org/gitlab/-/issues/333598#note_604529347) there on June 18th! 
I had been getting e-mail notifications since then (and reading them inside my e-mail client), but when I lately went to read one of them in my UXP-based browser, I discovered that **standalone-issue pages** now load blank, with the error being the one @dilworks posted 👍 

While the linked GL issue encompasses several aspects of GitLab breakage on "legacy" browsers (mostly due to usage of **Web Components**), the type of "talk" used by several GL devs (and it's funny how one team passes the "ball" to another...) is fully reflective of the way "things" have been driving to over the last year (or more), i.e. an **exclusive Chromium-based browser monopoly**... 😠 

Well, that issue, after a lot of back-and-forth, was finally closed yesterday (unsurprisingly as **WONT-FIX**): 
https://gitlab.com/gitlab-org/gitlab/-/issues/333598#note_678052585
i.e. infinitesimal GitLab traffic from "legacy" browsers, that doesn't warrant the time and effort on their part... 

> it requires RegExp engine update **in the browser**.

Unfortunately, too late for **UXP**-based browsers 😭 ; UXP has been put on permafrost, its successor (and resultant browser[s]) will be hidden behind **Private** repos... 😠 
https://forum.palemoon.org/viewtopic.php?p=220136#p220136

> you can get rid of the regex above using the Modify HTTP Response with the following filter:

Tested to work, at least with regards to opening **standalone** GitLab-issue pages; will have to further test whether other parts are affected (though not a massive GL user myself) ...
Many thanks, indeed 🎉 
Is there any programming chance that this "dirty workaround" be incorporated inside the `github-wc-polyfill` extension?

Kindest regards, thank you so much for your work on "legacy" browsers 👍 😃 .

**Comment by JustOff** [comment]
> Unfortunately, too late for UXP-based browsers

Well, recently @hawkeye116477 managed to port the necessary changes to Waterfox Classic (https://github.com/WaterfoxCo/Waterfox/pull/2192, https://github.com/WaterfoxCo/Waterfox/pull/2229), so there is a chance that @roytam1 and SeaMonkey devs will be able to follow this path too.

> Is there any programming chance that this "dirty workaround" be incorporated inside the `github-wc-polyfill` extension?

I was able to figure out [what exactly the regular expression above does](https://gitlab.com/gitlab-org/gitlab/-/commit/5522a5ffb6a0522e11dd684cce5c5e99ae6c24ce), and as a result to make the workaround not so dirty, so yes, I will include it into the next `github-wc-polyfill` release.

**Comment by hawkeye116477** [comment]
> SeaMonkey devs will be able to follow this path too

Well, I got message from Seamonkey dev:
> Hi just saw your comment in the regexp pull. Great work btw. I was about to
start it too but you did beat me to it.

So I assume that will be soon also on Seamonkey.

**Comment by roytam1** [comment]
> so there is a chance that @roytam1 and SeaMonkey devs will be able to follow this path too.

some of grounding work has been done by UXP developers in https://repo.palemoon.org/mcp-graveyard/UXP/commits/branch/new-regexp-hookup
it compiles with vc2017, but browser crashes when starting up. some more work will be required for fixing the crash.

**Comment by JustOff** [comment]
Apparently the [MCP solution](https://repo.palemoon.org/mcp-graveyard/UXP/issues/1800) is at the moment just incomplete.

<details>
 <summary>#1800 snapshot</summary>

![palemoon_2021-09-23_21-05-02](https://user-images.githubusercontent.com/340855/134560820-d28f4463-9981-40d8-a473-fb081aaf6963.png)
</details>

Perhaps the changes in the Waterfox Classic tree can help.
