### ISSUE TITLE
Commenting on StackOverflow no longer works

### ISSUE THREAD

**Issue by Reino17** [JustOff/github-wc-polyfill#51]
I understand this add-on primarily focuses on Github and Gitlab, but I was wondering if you could also have a look at stackoverflow.com.

Recently I believe they've updated their (or third-party?) javascript code, after which adding comments and using the "Show # more comments"-button don't work anymore.  
Also the preview-window for posting answers is at a bare minimum. No layout-buttons, nothing. If you'd carefully prepare your answer with Markdown syntax somewhere else, copy-paste it on StackOverflow and hit the "Post Your Answer"-button, then the answer might still be posted, but I haven't tested it.

I'm using [palemoon-28.10.4a1.win32-git-20220226-ba47fad4d-uxp-c403014cb-xpmod-sse.7z](http://o.rthost.win/palemoon/palemoon-28.10.4a1.win32-git-20220226-ba47fad4d-uxp-c403014cb-xpmod-sse.7z) and the "Error Console" reports:
```
SyntaxError: expected expression, got '.'
https://cdn.sstatic.net/Js/full.en.js?v=a230c14f22c0   (Line: 1, Column: 73115)
arams.delete("page"),n.searchParams.delete("tab");const s=n?.toString().replace(/#.*$/,"");window.location.href=s+"#tab-
```

**Comment by SeaHOH** [comment]
There has no method to make polyfill for optional chaining operators. So, only direct replace unique target in scripts can be work.

**Comment by Reino17** [comment]
I have no idea what you mean. Thanks for having a look, I guess?

**Comment by SeaHOH** [comment]
No polyfill means a lot of time and energy for long time support.

**Comment by dirkf** [comment]
UXP browser maintainers have to implement the ECMAScript 2020 optional chaining operator, by which time some other breaking syntax change may well have swept the fickle JS world.

**Comment by Vangelis66** [comment]
> I have no idea what you mean

... **SO** moved on to using quite recent Javascript code (as told by **dirkf**, [optional chaining operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining), (?.)), that is not currently supported natively by the **UXP** platform and its forks (hence your copy of **NM28**...); FWIW, it was first implemented in Chromium **80**/ Firefox **74**...
As to the prospect of **official** UXP devs implementing it natively in the platform, well, don't hold your breath (it might happen, but no-one knows when) 😉 ...  

As for **polyfills**, these are pieces of JS code written in older, backwards-compatible, syntax, that aim to do the same as the new, non-compatible code... 
Think of it that way: Say you have an old pocket calculator (I'm old enough to remember the CASIO ones 😄 ) which lacks a `x^y` button, and you're asked to calculate the value of 3^4; well, since your rudimentary calculator does have the multiply (`x`) button, you'd "polyfill" 3^4 with 3x3x3x3 ... 😜 
Polyfills can be injected by browser extensions to do the "job" the browser doesn't support natively - but, as said by **SeaHOH**, not all newer JS code can be polyfill-ed, and, sadly, this is true for (?.) that **SO** started using; it isn't beyond the realm of feasibility to address it now in UXP, rather **extremely difficult**, not worth the time and effort of an extension maintainer...  

If you're heavily reliant on **SO**, then why don't you let them know of your predicament directly? Perhaps they'd care to somehow address it (but most probably they won't 😞 )... 

`<small rant>`
I think those of us who, for whatever reasons, can't/won't use the **latest Chrome** iteration, have now come to the realisation UXP has pretty much reached the end of its journey webcompatibility-wise; 2022 is a crucial year, as the big "players" (mostly youth-oriented, "trendy", social-networked "portals") will progressively (and, alas, inevitably) switch to ECMAScript 2020/2022 standards, UXP won't be able to render them correctly, if at all... Saved by your smart phone, then? 😃 
`</small rant>`

**Comment by Reino17** [comment]
Thanks a lot for your elaborate answer, Vangelis66! To some extent I knew that NM28 (and all Palemoon browsers if I'm correct) are not up-to-date "webcompatibility-wise" to Chrome and Firefox (and probably never will), but as browser-development isn't one of my primary areas of interest, I didn't know what polyfills were to be honest... until now. Thanks.

> _if your old "pocket calculator" doesn't come with a **square root** (`√`) button, it'd be very **difficult** (if not **impossible**) to calculate square roots with the existing buttons..._

If it _does_ have a `x^y` button, then you could of course do `x^0.5`. ;)

**Comment by dirkf** [comment]
Yes, but RL is preventing me from spending the concentrated time needed ATM. RSN, anyway.

**Comment by Vangelis66** [comment]
> Thanks a lot for your elaborate answer, Vangelis66! 

You are welcome (being a beneficiary of your `ffmpeg` builds :+1: , I try to reciprocate :wink: ) :smile: . 

> If it does have a `x^y` button, then you could of course do x^0.5. ;)

Not the type of cheap "pocket calculators" I had in mind (mid-70s models); the common ones came without a `√` button and certainly without a `x^y` button :stuck_out_tongue_winking_eye: ; it was only the "scientific calculators" (I recollect owning a **Texas Instruments** one in the early 80s) that came with both `√`+`x^y`, no model I can remember had the latter but not the former...

> since we're using this repo's comments for **off-topic talk anyway**:

While I do agree that this very issue is OT in itself (as it doesn't pertain to either **GitHub**/**GitLab**), I do feel that my references to **polyfills** and  **UXP** remain relevant to this extension :wink: ; **polyfills** are an integral part of its code, **UXP** a supported application platform... 
My "pocket calculator" **analogy** (and related follow-up comment) was just a means to make my polyfill explanation attempt more "layman-ish" :wink: ; surely I shouldn't be blamed for that, should I?

**Comment by rofl0r** [comment]
as far as this very issue is concerned, there's a new addon called palefill https://github.com/martok/palefill - the author seems to be quite skilled and responsive, he fixed the godbolt site for me within an hour or 2 of me requesting it.
