### ISSUE TITLE
Notion Site is blank

### ISSUE THREAD

**Issue by Symbian9** [JustOff/github-wc-polyfill#56]
I'm not sure that this is directly `github-wc-polyfill` issue, but net site is just shown in *Pale Moon* as blank white page:

- https://djinni.notion.site/Remote-tech-jobs-for-Ukraine-b7f0f216ca6a419e920b5bc8a0489949

### Details
- **OS/Platform:** Linux / Debian 10 stretch
- **Pale Moon version:** `29.4.4`
- `github-wc-polyfill` version: `1.2.16`

**Comment by SeaHOH** [comment]
You can simply do a test without this addon.

**Comment by Symbian9** [comment]
So, issue this is general Pale Moon issue.

Got it.

**Comment by Vangelis66** [comment]
`https://*.notion.*/*` URLs are **not** in any way connected to either **GitHub**/**GitLab**, nor did they ever require the presence of **this extension** to load in a **UXP**-based browser... 

I, too, frequently use:  

`https://www.notion.so/venomissimo/34dc4ddf501a4b98b46ea9fb4f3470af`

and while that one used to load **OK** in my **Serpent 52** copy some time ago, it now also yields a blank page, with:  
```
SyntaxError: missing ( after for    app-6eec4a2fbd5acba8d6d3.js:1:5507619
```
displayed in the Web Console 😞 ; most probably, `notion` have recently updated to Chrome-specific recent JS syntax, not palatable to **current UXP**... :sob:

I guess it won't hurt to post in:  
[Pale Moon forum - Web Compatibility Support](https://forum.palemoon.org/viewforum.php?f=70&sid=cc19c38f65709cfe11f89de42df32b62)
to make the **official UXP** devs aware (but don't expect there's much they can do right away... ).

Additionally, you might want to ask in 

https://github.com/martok/palefill

since the author of that extension [is said to be willing to provide support for other sites](https://github.com/JustOff/github-wc-polyfill/issues/51#issuecomment-1061273056), too, beyond GitHub/GitLab... 😉  

Kind regards 😄

**Comment by Symbian9** [comment]
@Vangelis66, Thank You for details & for pointing me in right direction!
