### ISSUE TITLE
Add IceApe-UXP and BOC/UXP to install.rdf

### ISSUE THREAD

**Issue by RamonUnch** [JustOff/github-wc-polyfill#57]
I do use the polyfill add-on on the IceApe-UXP bower built by @roytam1
The browser being UXP based, it works flawlessly, same deal with the BOC/UXP (bnavigator.exe) also often build by from roytam1.

Could those two browsers be added to the install.rdf file so that people do not have to edit it manually every time? This is what I do for now.
It would look something like this:

``` 
    <!-- ICEAPE-UXP -->
    <em:targetApplication>
        <Description>
            <em:id>{9184b6fe-4a5c-484d-8b4b-efbfccbfb514}</em:id>
            <em:minVersion>52.9.*</em:minVersion>
            <em:maxVersion>52.*</em:maxVersion>
        </Description>
    </em:targetApplication>

    <!-- BNAVIGATOR (BOC/UXP) -->
    <em:targetApplication>
      <Description>
        <em:id>{a3210b97-8e8a-4737-9aa0-aa0e607640b9}</em:id>
        <em:minVersion>0.9.0a1</em:minVersion>
        <em:maxVersion>2.*</em:maxVersion>
      </Description>
    </em:targetApplication> 
```
I do not know your position on roytam builds, I completely understand if you do not want to support those forks.

**Comment by AroKol78** [comment]
it would be fun, but I suspect it is not in line with the development vision of the add-on (see https://github.com/JustOff/github-wc-polyfill/issues/21)

**Comment by RamonUnch** [comment]
I understand for Borealis Navigator but then what about IceApe-UXP? this latter does not have hidden source, it can be found [here](https://wiki.hyperbola.info/doku.php?id=en:system:application:uxp:iceape-uxp).  has not been updated since 2020 but built alongside the latest UXP everything works fine.

**Comment by rofl0r** [comment]
> (see https://github.com/JustOff/github-wc-polyfill/issues/21 , https://github.com/JustOff/github-wc-polyfill/issues/1 , https://github.com/JustOff/github-wc-polyfill/pull/23 , https://github.com/JustOff/github-wc-polyfill/issues/36 , https://github.com/JustOff/github-wc-polyfill/issues/18)

pointing this out isn't helpful. this repo is under new management now so let's hope  we're no longer keeping a hard stance but instead help each other.

**Comment by AroKol78** [comment]
so far I see a new co-creator, not a new manager (I hope that JustOff will come back safe and healthy)

**Comment by Vangelis66** [comment]
> but then what about **IceApe-UXP**?

#21 would still apply (`appVersion` doesn't change with newer builds, only `buildID` does...) 

With reference to the `BNav` fork, this has been a cause of constant ugly friction between the author of **official** `Borealis Navigator` and Roy, because that browser (currently private-sourced), to the best of my knowledge, has not been officially released in binary (executable) forms, yet... So, it would be prudent not to add more fuel to this controversy 😉 ; else, I fear a repetition of the "**MyPal** kerfuffle" which, believe me, will be detrimental for many, including the "retrocomputing" communities...

> this repo is under new management now

> so far I see a new co-creator, not a new manager 

![sh](https://user-images.githubusercontent.com/9669492/157785865-e459eff9-ace3-4ba7-a87d-d32fc82a5111.JPG)

IOW, **JustOff** (wishing him all the best ❤️ , hope he's safe) left someone in his shoes (so that us, mere users, don't end up stranded) for the duration (hopefully) war duties take precedence over coding... 
Thanks to him for sharing "maintainership" of this life-saving extension, many thanks to **SeaHOH**, too, for taking up the baton 👍 ...

Peace all, cheers 😄

**Comment by Vangelis66** [comment]
> **JustOff** (wishing him all the best ❤️ , hope he's safe) left someone in his shoes

![Capture2](https://user-images.githubusercontent.com/9669492/158040305-068f31c2-70ee-4bba-82d4-1a3eaae6ccf5.JPG)

😞

**Comment by RamonUnch** [comment]
Well I guess versioning is too much of a mess in IceApe-UXP to consider this anyway. People will just have to manually edit the `install.rdf` files, this is no big deal for me anyway.
