### ISSUE TITLE
TypeError: o.load is not a function

### ISSUE THREAD

**Issue by Reino17** [JustOff/github-wc-polyfill#61]
I'm using [palemoon-28.10.5a1.win32-git-20220402-ba47fad4d-uxp-21d56c9c9-xpmod-sse.7z](https://o.rthost.win/palemoon/palemoon-28.10.5a1.win32-git-20220402-ba47fad4d-uxp-21d56c9c9-xpmod-sse.7z) and [github-wc-polyfill-1.2.18.1.xpi](https://github.com/JustOff/github-wc-polyfill/releases/download/1.2.18/github-wc-polyfill-1.2.18.1.xpi).

https://github.com/JustOff/github-wc-polyfill is loading okay-ish (not everything works or is loaded correctly), unlike my own hobby-project https://github.com/Reino17/xivid/ where for instance all the commit-messages and corresponding dates aren't loaded. Instead I'm getting the familiar grey-ish animated loading banners (I don't know how else to describe it) with 100% cpu utilization as a result.

The different errors I see in the Error Console:
```
Error: TypeError: o.load is not a function
Source File: https://github.githubassets.com/assets/behaviors-de3cad11098f.js
Line: 10

Error: TypeError: t is undefined
Source File: https://github.githubassets.com/assets/command-palette-ce1d7f1bc262.js
Line: 1

Error: TypeError: t.dismiss is not a function
Source File: https://github.githubassets.com/assets/behaviors-de3cad11098f.js
Line: 87
```

Also the "Preview"-button to check this very post I'm writing doesn't work.

**Comment by SeaHOH** [comment]
Plz try a clear profile that only installed this addon.

**Comment by AroKol78** [comment]
I have no errors (St52 20220402) - it's ok on the same `js` names

**Comment by Reino17** [comment]
With a clean profile the issues disappeared indeed. That's a first (for me).

I don't supposed there's a way to pinpoint the culprit within my profile (instead of having to fully setup my profile again with add-ons, layout, settings, etc.)?

**Comment by SeaHOH** [comment]
You may check your user-scripts, or recently installed addons.

**Comment by Vangelis66** [comment]
> I don't suppose there's a way to pinpoint the culprit within my profile 
> (instead of having to fully setup my profile again with add-ons, layout, settings, etc.)?

Standard troubleshooting practices should apply here; the culprit could very well be:
1. One (or more) of the rest of the installed extensions - even custom/user modified preference/option of such an extension...
2. One of user-modified **browser prefs**, either via the browser GUI or via `about:config`

It is very common for "privacy/security"-oriented users to "tweak" the browser or add content/script blockers galore (to have a sense of additional "perceived" security), to such an extent that they actually cause more issues than the ones advertised to solve...

Disable all extensions except for `gh-wc-pf`, then restart the browser - **NoScript** is known to afflict permanent issues, even when disabled, so you should completely uninstall it before the rest of your troubleshooting... 
If the issue is rectified, then it's caused by one of your extensions - repeat the procedure by enabling one additional extension at a time and then restarting, until the issue manifests anew - then you will have found the culprit extension 😉 

If the issue persists (with all other extensions disabled), then the culprit lies inside your modded browser prefs; open `about:config` and sort according to user-set (bold); you should reset one-by-one and check if the breakage is mitigated (obviously, this will take some time, depending on the number of user-modified entries - it's best to note down the existing value of a user-set pref, in case you want to restore it...)

In general, **there's no easy/quick way** to easily discover the cause of a profile "breakage"; often times it's best to bite the bullet and start from scratch (many times a blessing in disguise, because doing so you get rid of many remnants from previous/older browser versions, littering your current "dirty" profile...). 

> the "Preview"-button to check this very post I'm writing doesn't work.

`Preview` functions require the `AbortController` API; make sure `dom.abortController.enabled` is in its default value of `true` ...

**Comment by Reino17** [comment]
I'm amazed by the amount of time and dedication you spend on your posts. Not only here, but especially on MSFN. Thanks!
> _often times it's best to bite the bullet and start from scratch [...]_

At first I thought about deleting all Github related cookies before unintalling any add-ons, but then I realized that one of those very Github related cookies is actually keeping me logged in at the moment. The profile-menu on Github doesn't work because of the issues I'm facing, so I can't even log out (and back in).

When I have the time I'll create and setup a new profile. I think it's indeed the wisest thing to do.
> _`dom.abortController.enabled`_

It's set to `true`.

**Comment by Vangelis66** [comment]
> When I have the time I'll create and setup a new profile. 

... Be **very careful** when you do that; my suggestion still stands as above, i.e. try to isolate the extension/extension setting/browser setting that causes the `gh-wc-pf` failure on your current profile; if not, you may again arrive in a **freshly rebuilt profile with the exact same issue** :sob:; happened to me in the past, so writing from (bad) experience... FWIW, having been for ca. 5 years a Firefox Nightly Tester, rebuilding Mozilla application profiles is a task that doesn't intimidate me at all... 

> I'm amazed by the amount of time and dedication you spend on your posts. [...] Thanks! 

You are most welcome 😄 ; I'm not a fan of one-liners myself, which seems to be against "la mode du jour", what with various chat-rooms, Discord, Twitter and the like... This has gained me an equal amount of "friends" and "haters", though... 😞 

I belong to a, perhaps, long gone era (that started for me with mailing lists), when concise/detailed guides/instructions were worth a lot more than today's practices of posting cryptic (to the non-savvy) messages and bare URLs (intended for self-help of OP); also, "scripta manent"; I have often had Google return as search result one of my past detailed posts (sometimes so old I forgot I wrote it in the first place 😜 😊 ), so it's nice to write "a gift that keeps on giving"... 

Sadly, GitHub issue trackers **are not intended as knowledge bases** (especially for topics external to their repo), so am afraid whenever I make elaborate/"dedicated" posts in the context of an issue comment, I am in fact in breach of "proper" netiquette and under "the sufferance" of the repo's owner... 

In any case, best of luck in creating a new and functioning **NM28** profile! 😺
